site_name: BTP Sextant Documentation
site_author: BTP
theme: readthedocs
copyright: Copyright &copy; 2021 Blockchain Technology Partners
nav:
  - Home: index.md
  - Clusters:
    - Overview: clusters/overview.md
    - Management: clusters/management.md
  - Deployments:
    - Overview: deployments/overview.md
    - Management: deployments/management.md
    - Distributed Ledgers:
      - Overview: deployments/dlts/overview.md
      - Besu:
        - Deployment: deployments/dlts/besu.md
      - Sawtooth:
        - Deployment: deployments/dlts/sawtooth.md
        - Services: deployments/dlts/sawtooth-services.md
    - Smart Contracts:
      - Overview: deployments/smart-contracts/overview.md
      - Daml on Besu: deployments/smart-contracts/daml-on-besu.md
      - Daml on Sawtooth: deployments/smart-contracts/daml-on-sawtooth.md
      - Daml on QLDB: deployments/smart-contracts/daml-on-qldb.md
      - Daml on Postgres: deployments/smart-contracts/daml-on-postgres.md
    - Information Security:
      - Overview: deployments/infosec/overview.md
      - TFS on Sawtooth: deployments/infosec/tfs-on-sawtooth.md
  - Users:
    - Overview: users/overview.md
    - Operations: users/management.md
  - Admin:
    - Overview: admin/overview.md
    - Operations: admin/operations.md
  - Advanced Topics:
    - EKS Clusters: topics/eks-clusters.md
    - Installation: topics/sextant-installation.md
    - AWS Marketplace Integration: topics/eks-cluster-aws-marketplace.md
    - Enabling Daml on QLDB: topics/eks-cluster-aws-services.md
    - Utility Deployments: topics/utility-deployments.md
