---
site_name: sextant
site_author: BTP
theme:
  name: material
  palette:
    scheme: default
copyright: Copyright &copy; 2022-23 Blockchain Technology Partners
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - Editions: editions.md
  - Installation:
      - Overview: installation/overview.md
      - Enterprise: installation/enterprise.md
      - AWS Marketplace:
          - Enterprise: installation/aws-enterprise.md
          - Premium: installation/aws-premium.md
          - Standard: installation/aws-standard.md
      - Community: installation/community.md
      - Access: installation/access.md
  - Clusters:
      - Overview: clusters/overview.md
      - Management: clusters/management.md
  - Deployments:
      - Overview: deployments/overview.md
      - Management: deployments/management.md
      - Distributed Ledgers:
          - Overview: deployments/dlts/overview.md
          - Besu:
              - Deployment: deployments/dlts/besu.md
              - Services: deployments/dlts/besu-services.md
#          - Fabric:
#              - Deployment: deployments/dlts/fabric.md
#              - Services: deployments/dlts/fabric-services.md
          - Sawtooth:
              - Deployment: deployments/dlts/sawtooth.md
              - Services: deployments/dlts/sawtooth-services.md
      - Provenance:
          - Overview: deployments/provo/overview.md
          - Chronicle on Sawtooth: deployments/provo/chronicle-on-sawtooth.md
      - Smart Contracts:
          - Overview: deployments/smart-contracts/overview.md
          - Daml on Besu: deployments/smart-contracts/daml-on-besu.md
          - Daml on Sawtooth: deployments/smart-contracts/daml-on-sawtooth.md
          - Daml on QLDB: deployments/smart-contracts/daml-on-qldb.md
          - Daml on Postgres: deployments/smart-contracts/daml-on-postgres.md
          - Daml Ledger Admin: deployments/smart-contracts/daml-ledger-admin.md
          - Daml Services: deployments/smart-contracts/daml-services.md
#      - Information Security:
#          - Overview: deployments/infosec/overview.md
#          - TFS™ on Sawtooth: deployments/infosec/tfs-on-sawtooth.md
#          - TFS™ Admin: deployments/infosec/tfs-admin.md
      - Utility:
          - Overview: topics/utility-deployments.md
  - Users:
      - Overview: users/overview.md
      - Operations: users/management.md
  - Admin:
      - Overview: admin/overview.md
      - Operations: admin/operations.md
